{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "\n",
        "!pip install git+https://github.com/LouiShadowMZ/quant-astro-lib.git\n",
        "\n",
        "import quant_astro as qa\n",
        "import swisseph as swe\n",
        "from quant_astro import create_dasha_table"
      ],
      "metadata": {
        "id": "IKnqugmURcR8",
        "collapsed": true
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "D33vzJ6aMPN1",
        "collapsed": true
      },
      "outputs": [],
      "source": [
        "# ----------------- 设置所有占星参数 -----------------\n",
        "chart_name = {\"matter_name\": \"喜欢的人是否会回头找我\"}\n",
        "\n",
        "birth_config = {\n",
        "    \"local_time_str\": \"2026-03-07 16:21:40.000000\", # 本地时间（必须含两位小数秒）\n",
        "    \"timezone_str\": \"+8:00\", # 时区（支持+8、-5:30、+5.5格式）\n",
        "    \"latitude_str\": \"23°01′59.170000″\", # 纬度（必须带两位小数秒）\n",
        "    \"longitude_str\": \"113°06′03.750000″\", # 经度（必须带两位小数秒）\n",
        "    \"elevation\": 0.0, # 海拔（米，两位小数）\n",
        "    \"atpress\": 1013.25, # 大气压\n",
        "    \"attemp\": 20.0, # 气温\n",
        "}\n",
        "\n",
        "calculation_options = {\n",
        "    \"ecliptic_mode\": 'sidereal', # 黄道模式：tropical/sidereal\n",
        "    \"ayanamsha_mode\": \"SIDM_KRISHNAMURTI\",\n",
        "    # 岁差体系（仅恒星黄道生效）SIDM_FAGAN_BRADLEY, SIDM_KRISHNAMURTI, SIDM_LAHIRI, SIDM_KRISHNAMURTI_VP291\n",
        "    \"node_mode\": 'mean', # 交点类型：true / mean\n",
        "    \"house_system\": 'Placidus', # 宫位制：[Placidus|Koch|Regiomontanus|Whole Sign|Equal|Campanus]\n",
        "    \"USE_HELIOCENTRIC\": True, # 日心制\n",
        "\n",
        "    # === 行星过滤 ===\n",
        "    # 选项：['Su', 'Mo', 'Me', 'Ve', 'Ma', 'Ju', 'Sa', 'Ur', 'Ne', 'Pl', 'Ra', 'Ke']，设置为 ['All'] 代表计算全部\n",
        "    # 迦勒底秩序： ['Su', 'Mo', 'Ma', 'Me', 'Ju', 'Ve', 'Sa', 'Ra', 'Ke'],\n",
        "    \"selected_planets\": ['Su', 'Mo', 'Me', 'Ve', 'Ma', 'Ju', 'Sa', 'Ra', 'Ke'],\n",
        "\n",
        "    # kp卜卦\n",
        "    \"KP_HORARY\": {\n",
        "    \"is_active\": True, # True / False 是否开启\n",
        "    \"mode\": \"KS-N\", # KS-N / CIL-N\n",
        "    \"number\": 142 # \"KS-N\"对应1-249之间整数，\"1-2193\"对应1-2193之间整数\n",
        "    }\n",
        "}\n",
        "\n",
        "# 日出与值日星\n",
        "sunrise_config = {\n",
        "    \"rsmi\": swe.CALC_RISE | swe.BIT_DISC_CENTER # 不设置参数则默认为上边缘\n",
        "                # swe.BIT_DISC_CENTER : 计算太阳中心点\n",
        "                # swe.BIT_DISC_BOTTOM : 计算太阳下边缘\n",
        "                # swe.BIT_NO_REFRACTION : 关闭大气折射修正，默认开启\n",
        "                # RISE SET\n",
        "}\n",
        "\n",
        "# 自定义点\n",
        "custom_points_config = {\n",
        "    \"福点 (Part of Fortune)\": 135.5,\n",
        "    \"我的幸运星\": 246.8,\n",
        "    \"一个特殊中点\": 310.12\n",
        "}\n",
        "\n",
        "# Dasha\n",
        "dasa_config = {\n",
        "    \"max_level\": 2,          # 计算层级：4代表计算到第四层\n",
        "    \"output_mode\": \"all\",    # 输出模式：\"all\"包含所有层级，\"present\"只包含当前最小层级\n",
        "    \"days_in_year\": 365.25   # Dasha计算中使用的年长度\n",
        "}\n",
        "\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# ----------------- 相位配置 -----------------\n",
        "\n",
        "# 2-1. 相位模式选择\n",
        "# 可选值: 'orb' (容许度), 'whole_sign' (整宫制), 'vedic' (印度)\n",
        "aspect_modes = ['orb', 'vedic']\n",
        "\n",
        "# 2-2. 基础容许度配置\n",
        "# 格式: \"行星:度数°分′秒″; ...\"\n",
        "orb_config_str = \"\"\"\n",
        "Su: 15°00′00″; Mo: 12°00′00″; Me: 7°00′00″; Ve: 7°00′00″;\n",
        "Ma: 8°00′00″; Ju: 9°00′00″; Sa: 9°00′00″;\n",
        "Ra: 0°00′00″; Ke: 0°00′00″;\n",
        "Ur: 5°00′00″; Ne: 5°00′00″; Pl: 5°00′00″\n",
        "\n",
        "# === 纯数字宫位容许度 ===\n",
        "1: 5°00′00″;  10: 5°00′00″\n",
        "\"\"\"\n",
        "\n",
        "# 2-3. 宫位选择 (仅容许度模式生效)\n",
        "# 输入要参与计算的宫位数字列表\n",
        "active_houses_list = [1, 10]\n",
        "\n",
        "# 2-4. 自定义相位类型\n",
        "# 格式: \"角度°符号\"，仅容许度模式生效\n",
        "custom_aspect_types = [\n",
        "    \"0°☌\",       # 合相\n",
        "    \"60°⚹\",      # 六分相\n",
        "    \"90°□\",      # 刑相\n",
        "    \"120°△\",     # 拱相\n",
        "    \"180°☍\",     # 冲相\n",
        "\n",
        "]\n",
        "\n",
        "# 赤纬设置\n",
        "declination_config = {\n",
        "    'is_active': False,\n",
        "    'orb': 1.2,\n",
        "    'parallel_sym': '∥',\n",
        "    'contra_sym': '∦'\n",
        "}\n",
        "\n",
        "# 打包配置字典\n",
        "aspect_config = {\n",
        "    'modes': aspect_modes,\n",
        "    'orb_config_str': orb_config_str,\n",
        "    'active_houses': active_houses_list,\n",
        "    'aspect_types': custom_aspect_types,\n",
        "    'declination': declination_config\n",
        "}\n",
        "\n"
      ],
      "metadata": {
        "id": "XYklijfeJW5F"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ----------------- 执行计算 -----------------\n",
        "\n",
        "# 核心计算：行星和宫头信息\n",
        "planet_pos, house_pos, ascmc_tuple, jd, dignities = qa.calculate_positions(\n",
        "    **birth_config,\n",
        "    **calculation_options\n",
        ")\n",
        "\n",
        "# ----------------- 属性计算：获取星座、落宫、宫主星 -----------------\n",
        "# 这是一个新步骤，调用 attributes.py 中的逻辑\n",
        "planet_signs, house_signs, planet_houses, house_lords = qa.get_attributes(\n",
        "    planet_pos,\n",
        "    house_pos\n",
        ")\n",
        "\n",
        "# 日出与值日星\n",
        "sunrise_results = qa.get_sun_rise_and_lord(birth_config, sunrise_config)\n",
        "\n",
        "# ----------------- 行星时 -----------------\n",
        "planetary_hour_data = qa.get_planetary_hour(birth_config, sunrise_config)\n",
        "\n",
        "# KP计算\n",
        "# 1. 获取KP星主\n",
        "kp_planet_results, kp_house_results = qa.get_kp_lords(planet_pos, house_pos)\n",
        "\n",
        "# 2. 象征星\n",
        "kp_planet_sigs, kp_house_sigs = qa.get_significators(planet_pos, house_pos, kp_planet_results, kp_house_results)\n",
        "\n",
        "# 3. 主宰星\n",
        "kp_ruling_planets = qa.get_ruling_planets(kp_planet_results, kp_house_results, sunrise_results['day_lord'])\n",
        "\n",
        "# 相位计算\n",
        "aspect_results = qa.calculate_aspects(planet_pos, house_pos, aspect_config)\n"
      ],
      "metadata": {
        "id": "X8hyJ6xMBsky"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ----------------- 准备数据 (方案一：扁平化字典) -----------------\n",
        "# 直接把所有信息写在一个字典里，不要嵌套的大括号 {}\n",
        "info_data = {\n",
        "    # --- 基本信息 ---\n",
        "    \"事项名称\": chart_name.get(\"matter_name\", \"-\"),\n",
        "\n",
        "    # --- 出生参数 ---\n",
        "    \"本地时间\": birth_config.get(\"local_time_str\", \"-\"),\n",
        "    \"时区\": birth_config.get(\"timezone_str\", \"-\"),\n",
        "    \"纬度\": birth_config.get(\"latitude_str\", \"-\"),\n",
        "    \"经度\": birth_config.get(\"longitude_str\", \"-\"),\n",
        "    # \"海拔\": birth_config.get(\"elevation\", 0),\n",
        "    # \"大气压\": birth_config.get(\"atpress\", 0),\n",
        "    # \"温度\": birth_config.get(\"attemp\", 0),\n",
        "\n",
        "    # --- 计算选项 ---\n",
        "    \"黄道模式\": calculation_options.get(\"ecliptic_mode\", \"-\"),\n",
        "\n",
        "    # 【插入点1】如果不是回归黄道，就在这里插入岁差体系\n",
        "    **({\"岁差体系\": calculation_options.get(\"ayanamsha_mode\", \"-\")}\n",
        "       if calculation_options.get(\"ecliptic_mode\") != 'tropical' else {}),\n",
        "\n",
        "    \"交点类型\": calculation_options.get(\"node_mode\", \"-\"),\n",
        "    \"宫位制\": calculation_options.get(\"house_system\", \"-\"),\n",
        "    \"启用日心制\": \"是\" if calculation_options.get(\"USE_HELIOCENTRIC\") else \"否\",\n",
        "\n",
        "    # 【插入点2】如果KP开启，仅插入 KP报数 (不再显示开关状态)\n",
        "    **({\"KP报数\": calculation_options.get(\"KP_HORARY\", {}).get(\"number\", \"-\")}\n",
        "       if calculation_options.get(\"KP_HORARY\", {}).get(\"is_active\") else {})\n",
        "}\n",
        "\n",
        "\n",
        "# ----------------- 生成 HTML -----------------\n",
        "output_file = \"astro_chart_final.html\"\n",
        "\n",
        "# 调用函数 (参数保持不变，但 chart_info 传入的是上面的中文版字典)\n",
        "qa.generate_chart_html(\n",
        "    planet_pos,\n",
        "    house_pos,\n",
        "    chart_info=info_data, # 传入这个扁平字典\n",
        "    kp_planet_results=kp_planet_results,\n",
        "    kp_house_results=kp_house_results,\n",
        "    kp_planet_sigs=kp_planet_sigs,\n",
        "    kp_house_sigs=kp_house_sigs,\n",
        "    kp_ruling_planets=kp_ruling_planets,\n",
        "\n",
        "    # === 新增传入 ===\n",
        "    aspect_results=aspect_results,       # 传入计算好的相位结果\n",
        "    aspect_config=aspect_config,         # 传入相位配置 (含 active_houses)\n",
        "    calculation_options=calculation_options, # 传入计算配置 (含 selected_planets)\n",
        "    # ================\n",
        "\n",
        "    output_filename=output_file\n",
        ")\n",
        "\n",
        "# 下载部分保持不变...\n",
        "\n",
        "# 自动触发下载 (Colab环境)\n",
        "try:\n",
        "    from google.colab import files\n",
        "    print(f\"✨ HTML 生成完毕，正在启动下载: {output_file}\")\n",
        "    files.download(output_file)\n",
        "except ImportError:\n",
        "    print(f\"✅ 文件已保存至本地: {output_file}\")"
      ],
      "metadata": {
        "id": "dz5PpltlwnTA",
        "collapsed": true
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ----------------- Dasa计算 -----------------\n",
        "# 将【第3步】计算出的 `planet_pos` 字典传入即可\n",
        "print(\"\\n--- 开始生成Dasha时间表 ---\")\n",
        "create_dasha_table(planet_pos, birth_config, dasa_config)"
      ],
      "metadata": {
        "id": "MisHZ3OiMrd9",
        "collapsed": true
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ----------------- 检查所有原始结果词典 -----------------\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 行星原始位置字典 (planet_pos) \" + \"=\"*20)\n",
        "for key, value in planet_pos.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 宫头原始位置字典 (house_pos) \" + \"=\"*20)\n",
        "for key, value in house_pos.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 字典1：行星的星座归属 (planet_signs) \" + \"=\"*20)\n",
        "for key, value in planet_signs.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 字典2：宫位的星座归属 (house_signs) \" + \"=\"*20)\n",
        "for key, value in house_signs.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 字典3：行星的宫位归属 (planet_houses) \" + \"=\"*20)\n",
        "for key, value in planet_houses.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 字典4：每个宫位的主宰星 (house_lords) \" + \"=\"*20)\n",
        "for key, value in house_lords.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"=\"*20 + \" KP行星结果字典 (kp_planet_results) \" + \"=\"*20)\n",
        "for key, value in kp_planet_results.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" KP宫位结果字典 (kp_house_results) \" + \"=\"*20)\n",
        "for key, value in kp_house_results.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 行星象征宫位 (kp_planet_sigs) \" + \"=\"*20)\n",
        "for key, value in kp_planet_sigs.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 宫位象征星 (kp_house_sigs) \" + \"=\"*20)\n",
        "for key, value in kp_house_sigs.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 主宰星字典 (kp_ruling_planets) \" + \"=\"*20)\n",
        "print(kp_ruling_planets)\n",
        "\n",
        "print(\"\\n\" + \"=\"*20 + \" 行星时数据 (Planetary Hour) \" + \"=\"*20)\n",
        "for key, value in planetary_hour_data.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "# === 【新增】打印庙旺陷落表 ===\n",
        "print(\"\\n\" + \"=\"*20 + \" 行星庙旺陷落配置 (Dignities) \" + \"=\"*20)\n",
        "for key, value in dignities.items():\n",
        "    print(f\"{key}: {value}\")\n",
        "\n",
        "# 打印相位计算的原始结果字典\n",
        "print(\"\\n\" + \"=\"*20 + \" 原始相位数据 (aspect_results) \" + \"=\"*20)\n",
        "print(f\"aspect_results: {aspect_results}\")\n",
        "\n",
        "# 如果您想看分项的原始字典：\n",
        "if 'orb_mode' in aspect_results:\n",
        "    print(f\"\\norb_mode_list: {aspect_results['orb_mode']}\")\n",
        "\n",
        "if 'whole_sign_mode' in aspect_results:\n",
        "    print(f\"\\nwhole_sign_list: {aspect_results['whole_sign_mode']}\")\n",
        "\n",
        "if 'vedic_mode' in aspect_results:\n",
        "    print(f\"\\nvedic_mode_list: {aspect_results['vedic_mode']}\")\n",
        "\n",
        "\n",
        "# 日出与值日星字典===\n",
        "print(\"\\n\" + \"=\"*20 + \" 值日星字典（sunrise_results） \" + \"=\"*20)\n",
        "print(\"sunrise_results:\", sunrise_results)\n",
        "\n",
        "# 您甚至可以检查儒略日\n",
        "print(\"\\n\" + \"=\"*20 + \" 儒略日 (Julian Day) \" + \"=\"*20)\n",
        "print(jd)"
      ],
      "metadata": {
        "id": "bX0U8OlvOKTQ"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}