# -*- coding: utf-8 -*-
"""调用.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UPPlNp2KK2RwKNAdMW8wVk05KkMsl35
"""

!pip install git+https://github.com/LouiShadowMZ/quant-astro-lib.git

import quant_astro as qa
import swisseph as swe
from quant_astro import create_dasha_table

# ----------------- 设置所有占星参数 -----------------
chart_name = {"matter_name": "澳大利亚留学女朋友"}

birth_config = {
    "local_time_str": "2026-02-12 20:51:37.000000", # 本地时间（必须含两位小数秒）
    "timezone_str": "+8:00", # 时区（支持+8、-5:30、+5.5格式）
    "latitude_str": "23°02′00.000000″", # 纬度（必须带两位小数秒）
    "longitude_str": "113°06′00.000000″", # 经度（必须带两位小数秒）
    "elevation": 0.0, # 海拔（米，两位小数）
    "atpress": 1013.25, # 大气压
    "attemp": 20.0, # 气温
}

calculation_options = {
    "ecliptic_mode": 'tropical', # 黄道模式：tropical/sidereal
    "ayanamsha_mode": "SIDM_KRISHNAMURTI",
    # 岁差体系（仅恒星黄道生效）SIDM_FAGAN_BRADLEY, SIDM_KRISHNAMURTI, SIDM_LAHIRI, SIDM_KRISHNAMURTI_VP291
    "node_mode": 'mean', # 交点类型：true / mean
    "house_system": 'Regiomontanus', # 宫位制：[Placidus|Koch|Regiomontanus|Whole Sign|Equal|Campanus]
    "USE_HELIOCENTRIC": True, # 日心制

    # === 行星过滤 ===
    # 选项：['Su', 'Mo', 'Me', 'Ve', 'Ma', 'Ju', 'Sa', 'Ur', 'Ne', 'Pl', 'Ra', 'Ke']，设置为 ['All'] 代表计算全部
    # 迦勒底秩序： ['Su', 'Mo', 'Ma', 'Me', 'Ju', 'Ve', 'Sa', 'Ra', 'Ke'],
    "selected_planets": ['Su', 'Mo', 'Me', 'Ve', 'Ma', 'Ju', 'Sa', 'Ra', 'Ke'],

    # kp卜卦
    "KP_HORARY": {
    "is_active": False, # True / False 是否开启
    "mode": "KS-N", # KS-N / CIL-N
    "number": 53 # "KS-N"对应1-249之间整数，"1-2193"对应1-2193之间整数
    }
}

# 日出与值日星
sunrise_config = {
    "rsmi": swe.CALC_RISE | swe.BIT_DISC_CENTER # 不设置参数则默认为上边缘
                # swe.BIT_DISC_CENTER : 计算太阳中心点
                # swe.BIT_DISC_BOTTOM : 计算太阳下边缘
                # swe.BIT_NO_REFRACTION : 关闭大气折射修正，默认开启
}

# 自定义点
custom_points_config = {
    "福点 (Part of Fortune)": 135.5,
    "我的幸运星": 246.8,
    "一个特殊中点": 310.12
}

# Dasha
dasa_config = {
    "max_level": 2,          # 计算层级：4代表计算到第四层
    "output_mode": "all",    # 输出模式："all"包含所有层级，"present"只包含当前最小层级
    "days_in_year": 365.25   # Dasha计算中使用的年长度
}

# ----------------- 相位配置 -----------------

# 2-1. 相位模式选择
# 可选值: 'orb' (容许度), 'whole_sign' (整宫制), 'vedic' (印度)
aspect_modes = ['orb']

# 2-2. 基础容许度配置
# 格式: "行星:度数°分′秒″; ..."
orb_config_str = """
Su: 15°00′00″; Mo: 12°00′00″; Me: 7°00′00″; Ve: 7°00′00″;
Ma: 8°00′00″; Ju: 9°00′00″; Sa: 9°00′00″;
Ra: 0°00′00″; Ke: 0°00′00″;
Ur: 5°00′00″; Ne: 5°00′00″; Pl: 5°00′00″

# === 纯数字宫位容许度 ===
1: 5°00′00″;  10: 5°00′00″
"""

# 2-3. 宫位选择 (仅容许度模式生效)
# 输入要参与计算的宫位数字列表
active_houses_list = [1, 10]

# 2-4. 自定义相位类型
# 格式: "角度°符号"，仅容许度模式生效
custom_aspect_types = [
    "0°☌",       # 合相
    "60°⚹",      # 六分相
    "90°□",      # 刑相
    "120°△",     # 拱相
    "180°☍",     # 冲相

]

# 打包配置字典
aspect_config = {
    'modes': aspect_modes,
    'orb_config_str': orb_config_str,
    'active_houses': active_houses_list,
    'aspect_types': custom_aspect_types
}

# ----------------- 执行计算 -----------------

# 核心计算：行星和宫头信息
planet_pos, house_pos, ascmc_tuple, jd, dignities = qa.calculate_positions(
    **birth_config,
    **calculation_options
)

# ----------------- 属性计算：获取星座、落宫、宫主星 -----------------
# 这是一个新步骤，调用 attributes.py 中的逻辑
planet_signs, house_signs, planet_houses, house_lords = qa.get_attributes(
    planet_pos,
    house_pos
)

# 日出与值日星
sunrise_results = qa.get_sun_rise_and_lord(birth_config, sunrise_config)

# ----------------- 行星时 -----------------
planetary_hour_data = qa.get_planetary_hour(birth_config, sunrise_config)

# KP计算
# 1. 获取KP星主
kp_planet_results, kp_house_results = qa.get_kp_lords(planet_pos, house_pos)

# 2. 象征星
kp_planet_sigs, kp_house_sigs = qa.get_significators(planet_pos, house_pos, kp_planet_results, kp_house_results)

# 3. 主宰星
kp_ruling_planets = qa.get_ruling_planets(kp_planet_results, kp_house_results, sunrise_results['day_lord'])

# 相位计算
aspect_results = qa.calculate_aspects(planet_pos, house_pos, aspect_config)

# ----------------- 准备数据 (方案一：扁平化字典) -----------------
# 直接把所有信息写在一个字典里，不要嵌套的大括号 {}
info_data = {
    # --- 基本信息 ---
    "事项名称": chart_name.get("matter_name", "-"),

    # --- 出生参数 ---
    "本地时间": birth_config.get("local_time_str", "-"),
    "时区": birth_config.get("timezone_str", "-"),
    "纬度": birth_config.get("latitude_str", "-"),
    "经度": birth_config.get("longitude_str", "-"),
    # "海拔": birth_config.get("elevation", 0),
    # "大气压": birth_config.get("atpress", 0),
    # "温度": birth_config.get("attemp", 0),

    # --- 计算选项 ---
    "黄道模式": calculation_options.get("ecliptic_mode", "-"),

    # 【插入点1】如果不是回归黄道，就在这里插入岁差体系
    **({"岁差体系": calculation_options.get("ayanamsha_mode", "-")}
       if calculation_options.get("ecliptic_mode") != 'tropical' else {}),

    "交点类型": calculation_options.get("node_mode", "-"),
    "宫位制": calculation_options.get("house_system", "-"),
    "启用日心制": "是" if calculation_options.get("USE_HELIOCENTRIC") else "否",

    # 【插入点2】如果KP开启，仅插入 KP报数 (不再显示开关状态)
    **({"KP报数": calculation_options.get("KP_HORARY", {}).get("number", "-")}
       if calculation_options.get("KP_HORARY", {}).get("is_active") else {})
}


# ----------------- 生成 HTML -----------------
output_file = "astro_chart_final.html"

# 调用函数 (参数保持不变，但 chart_info 传入的是上面的中文版字典)
qa.generate_chart_html(
    planet_pos,
    house_pos,
    chart_info=info_data, # 传入这个扁平字典
    kp_planet_results=kp_planet_results,
    kp_house_results=kp_house_results,
    kp_planet_sigs=kp_planet_sigs,
    kp_house_sigs=kp_house_sigs,
    kp_ruling_planets=kp_ruling_planets,

    # === 新增传入 ===
    aspect_results=aspect_results,       # 传入计算好的相位结果
    aspect_config=aspect_config,         # 传入相位配置 (含 active_houses)
    calculation_options=calculation_options, # 传入计算配置 (含 selected_planets)
    # ================

    output_filename=output_file
)

# 下载部分保持不变...

# 自动触发下载 (Colab环境)
try:
    from google.colab import files
    print(f"✨ HTML 生成完毕，正在启动下载: {output_file}")
    files.download(output_file)
except ImportError:
    print(f"✅ 文件已保存至本地: {output_file}")

# ----------------- Dasa计算 -----------------
# 将【第3步】计算出的 `planet_pos` 字典传入即可
print("\n--- 开始生成Dasha时间表 ---")
create_dasha_table(planet_pos, birth_config, dasa_config)

# ----------------- 检查所有原始结果词典 -----------------

print("\n" + "="*20 + " 行星原始位置字典 (planet_pos) " + "="*20)
for key, value in planet_pos.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " 宫头原始位置字典 (house_pos) " + "="*20)
for key, value in house_pos.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " 字典1：行星的星座归属 (planet_signs) " + "="*20)
for key, value in planet_signs.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " 字典2：宫位的星座归属 (house_signs) " + "="*20)
for key, value in house_signs.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " 字典3：行星的宫位归属 (planet_houses) " + "="*20)
for key, value in planet_houses.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " 字典4：每个宫位的主宰星 (house_lords) " + "="*20)
for key, value in house_lords.items():
    print(f"{key}: {value}")

print("="*20 + " KP行星结果字典 (kp_planet_results) " + "="*20)
for key, value in kp_planet_results.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " KP宫位结果字典 (kp_house_results) " + "="*20)
for key, value in kp_house_results.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " 行星象征宫位 (kp_planet_sigs) " + "="*20)
for key, value in kp_planet_sigs.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " 宫位象征星 (kp_house_sigs) " + "="*20)
for key, value in kp_house_sigs.items():
    print(f"{key}: {value}")

print("\n" + "="*20 + " 主宰星字典 (kp_ruling_planets) " + "="*20)
print(kp_ruling_planets)

print("\n" + "="*20 + " 行星时数据 (Planetary Hour) " + "="*20)
for key, value in planetary_hour_data.items():
    print(f"{key}: {value}")

# === 【新增】打印庙旺陷落表 ===
print("\n" + "="*20 + " 行星庙旺陷落配置 (Dignities) " + "="*20)
for key, value in dignities.items():
    print(f"{key}: {value}")

# 打印相位计算的原始结果字典
print("\n" + "="*20 + " 原始相位数据 (aspect_results) " + "="*20)
print(f"aspect_results: {aspect_results}")

# 如果您想看分项的原始字典：
if 'orb_mode' in aspect_results:
    print(f"\norb_mode_list: {aspect_results['orb_mode']}")

if 'whole_sign_mode' in aspect_results:
    print(f"\nwhole_sign_list: {aspect_results['whole_sign_mode']}")

if 'vedic_mode' in aspect_results:
    print(f"\nvedic_mode_list: {aspect_results['vedic_mode']}")


# 日出与值日星字典===
print("\n" + "="*20 + " 值日星字典（sunrise_results） " + "="*20)
print("sunrise_results:", sunrise_results)

# 您甚至可以检查儒略日
print("\n" + "="*20 + " 儒略日 (Julian Day) " + "="*20)
print(jd)

# ----------------- 执行并美观打印相位结果 -----------------

print("\n" + "🚀 相位计算结果 (Aspects Report)".center(60, "="))

# 辅助函数：打印分隔线
def print_separator(width=60):
    print("-" * width)

# 1. 容许度模式输出
if 'orb_mode' in aspect_results and aspect_results['orb_mode']:
    count = len(aspect_results['orb_mode'])
    print(f"\n[📡 容许度模式 (Orb Mode)] - 共 {count} 条记录")
    print_separator(75)
    # 定义表头：<左对齐, >右对齐, ^居中
    # P1(5) P2(5) Sym(4) State(4) Angle(10) Orb(12) Definition(10)
    header = f"{'P1':<5} {'P2':<5} {'Sym':^5} {'St.':^5} {'Actual':>10} {'Orb':>12} {'Def':>10}"
    print(header)
    print_separator(75)

    for row in aspect_results['orb_mode']:
        p1 = row['p1']
        p2 = row['p2']
        sym = row['type']
        st = row['state']

        # 精度控制
        actual = f"{row['actual_dist']:.4f}°" # 实际角度
        orb_val = f"{row['orb']:.6f}°"        # 容许度误差
        defn = f"{row['angle_def']:.0f}°"     # 定义角度(如90)

        print(f"{p1:<5} {p2:<5} {sym:^5} {st:^5} {actual:>10} {orb_val:>12} {defn:>10}")

# 2. 整宫制模式输出
if 'whole_sign_mode' in aspect_results and aspect_results['whole_sign_mode']:
    count = len(aspect_results['whole_sign_mode'])
    print(f"\n[🏛️ 整宫制模式 (Whole Sign)] - 共 {count} 条记录")
    print_separator(40)
    print(f"{'Planet 1':<10} {'Aspect':^8} {'Planet 2':<10} {'State':<5}")
    print_separator(40)

    for row in aspect_results['whole_sign_mode']:
        # 简单整洁的对齐
        print(f"{row['p1']:<10} {row['type']:^8} {row['p2']:<10} {row['state']}")

# 3. 印度模式输出
if 'vedic_mode' in aspect_results and aspect_results['vedic_mode']:
    count = len(aspect_results['vedic_mode'])
    print(f"\n[🕉️ 印度模式 (Vedic Mode)] - 共 {count} 条视线")
    print_separator(50)
    print(f"{'Caster (施)':<12} {'Type':^10} {'Receiver (受)':<12}")
    print_separator(50)

    for row in aspect_results['vedic_mode']:
        # 箭头式表达，清晰直观
        print(f"{row['p1']:<12} --{row['type']}-->   {row['p2']:<12}")

print("\n" + "="*60)