{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "id": "IKnqugmURcR8"
   },
   "outputs": [],
   "source": [
    "!pip install git+https://github.com/LouiShadowMZ/quant-astro-lib.git\n",
    "\n",
    "import quant_astro as qa\n",
    "import swisseph as swe\n",
    "from quant_astro import create_dasha_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "id": "D33vzJ6aMPN1"
   },
   "outputs": [],
   "source": [
    "# ----------------- 设置所有占星参数 -----------------\n",
    "chart_name = {\"matter_name\": \"30 什么时候能找到工作\"}\n",
    "\n",
    "birth_config = {\n",
    "    \"local_time_str\": \"2026-08-20 20:47:00.000000\", # 本地时间（必须含两位小数秒）\n",
    "    \"timezone_str\": \"+8:00\", # 时区（支持+8、-5:30、+5.5格式）\n",
    "    \"latitude_str\": \"23°01′59.300000″\", # 纬度（必须带两位小数秒）23°01′59.300000″\n",
    "    \"longitude_str\": \"113°06′03.800000″\", # 经度（必须带两位小数秒）113°06′03.800000″\n",
    "    \"elevation\": 0.0, # 海拔（米，两位小数）\n",
    "    \"atpress\": 1013.25, # 大气压\n",
    "    \"attemp\": 20.0, # 气温\n",
    "    \"calendar\": \"g\",  # g = 格里历，j = 儒略历\n",
    "}\n",
    "\n",
    "calculation_options = {\n",
    "    \"ecliptic_mode\": 'tropical', # 黄道模式：tropical/sidereal\n",
    "    \"ayanamsha_mode\": \"SIDM_KRISHNAMURTI\", # 岁差体系（仅恒星黄道生效）FAGAN_BRADLEY | KRISHNAMURTI | LAHIRI | KRISHNAMURTI_VP291\n",
    "    \"node_mode\": 'mean', # 交点类型：true / mean\n",
    "    \"house_system\": 'Regiomontanus', # 宫位制：[ Placidus | Regiomontanus | Koch | Whole Sign | Equal| Campanus ]\n",
    "    \"USE_HELIOCENTRIC\": False, # 日心制\n",
    "\n",
    "    # === 行星过滤 ===\n",
    "    \"selected_planets\": ['Su', 'Mo', 'Me', 'Ve', 'Ma', 'Ju', 'Sa', 'Ra', 'Ke'],\n",
    "\n",
    "    # === 恒星配置 ===\n",
    "    # 设置为 [] 则不计算任何恒星\n",
    "    \"selected_stars\": [\n",
    "    \"Algol,bePer\",          # 1  大陵五（英仙座β）\n",
    "    \"Alcyone,etTau\",        # 2  昴宿六（金牛座η，昴星团代表星）\n",
    "    \"Aldebaran,alTau\",      # 3  毕宿五（金牛座α）\n",
    "    \"Capella,alAur\",        # 4  五车二（御夫座α）\n",
    "    \"Sirius,alCMa\",         # 5  天狼星（大犬座α）\n",
    "    \"Procyon,alCMi\",        # 6  南河三（小犬座α）\n",
    "    \"Regulus,alLeo\",        # 7  轩辕十四（狮子座α）\n",
    "    \"Algorab,deCrv\",        # 8  轸宿一（乌鸦座δ）\n",
    "    \"Spica,alVir\",          # 9  角宿一（室女座α）\n",
    "    \"Arcturus,alBoo\",       # 10 大角星（牧夫座α）\n",
    "    \"Alphecca,alCrB\",       # 11 贯索四（北冕座α）\n",
    "    \"Antares,alSco\",        # 12 心宿二（天蝎座α）\n",
    "    \"Vega,alLyr\",           # 13 织女一（天琴座α）\n",
    "    \"DenebAlgedi,deCap\",    # 14 垒壁阵四（摩羯座δ）\n",
    "    \"Fomalhaut,alPsA\",      # 15 北落师门（南鱼座α）\n",
    "    ],\n",
    "\n",
    "    # kp卜卦\n",
    "    \"KP_HORARY\": {\n",
    "    \"is_active\": False, # True / False 是否开启\n",
    "    \"mode\": \"KS-N\", # KS-N / CIL-N\n",
    "    \"number\": 78 # \"KS-N\"对应1-249之间整数，\"1-2193\"对应1-2193之间整数\n",
    "    }\n",
    "\n",
    "\n",
    "}\n",
    "\n",
    "# 日出与值日星\n",
    "sunrise_config = {\n",
    "    \"rsmi\": swe.CALC_RISE | swe.BIT_DISC_CENTER # 不设置参数则默认为上边缘\n",
    "                # swe.BIT_DISC_CENTER : 计算太阳中心点\n",
    "                # swe.BIT_DISC_BOTTOM : 计算太阳下边缘\n",
    "                # swe.BIT_NO_REFRACTION : 关闭大气折射修正，默认开启\n",
    "                # RISE SET\n",
    "}\n",
    "\n",
    "# Dasha\n",
    "dasa_config = {\n",
    "    \"max_level\": 2,          # 计算层级：4代表计算到第四层\n",
    "    \"output_mode\": \"all\",    # 输出模式：\"all\"包含所有层级，\"present\"只包含当前最小层级\n",
    "    \"days_in_year\": 365.25   # Dasha计算中使用的年长度\n",
    "}\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "X8hyJ6xMBsky"
   },
   "outputs": [],
   "source": [
    "# ----------------- 执行计算 -----------------\n",
    "\n",
    "# 核心计算：行星和宫头信息\n",
    "planet_pos, house_pos, ascmc_tuple, jd, dignities, minor_planet_pos = qa.calculate_positions(\n",
    "    **birth_config,\n",
    "    **calculation_options\n",
    ")\n",
    "\n",
    "\n",
    "# 恒星计算（从 calculation_options 里读取配置）\n",
    "fixed_star_pos = qa.calculate_fixed_stars(\n",
    "    jd_utc=jd,\n",
    "    selected_stars=calculation_options.get(\"selected_stars\", []),\n",
    "    ecliptic_mode=calculation_options[\"ecliptic_mode\"],\n",
    "    ayanamsha_mode=calculation_options[\"ayanamsha_mode\"]\n",
    ")\n",
    "\n",
    "\n",
    "# 日出与值日星\n",
    "sunrise_results = qa.get_sun_rise_and_lord(birth_config, sunrise_config)\n",
    "\n",
    "# ----------------- 行星时 -----------------\n",
    "planetary_hour_data = qa.get_planetary_hour(birth_config, sunrise_config)\n",
    "\n",
    "# KP计算\n",
    "# 1. 获取KP星主\n",
    "kp_planet_results, kp_house_results = qa.get_kp_lords(planet_pos, house_pos)\n",
    "\n",
    "# 2. 象征星\n",
    "kp_planet_sigs, kp_house_sigs = qa.get_significators(planet_pos, house_pos, kp_planet_results, kp_house_results)\n",
    "\n",
    "# 3. 主宰星\n",
    "kp_ruling_planets = qa.get_ruling_planets(kp_planet_results, kp_house_results, sunrise_results['day_lord'])\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "id": "MisHZ3OiMrd9"
   },
   "outputs": [],
   "source": [
    "# ----------------- Dasa计算 -----------------\n",
    "# 将【第3步】计算出的 `planet_pos` 字典传入即可\n",
    "print(\"\\n--- 开始生成Dasha时间表 ---\")\n",
    "create_dasha_table(planet_pos, birth_config, dasa_config)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "bX0U8OlvOKTQ"
   },
   "outputs": [],
   "source": [
    "# ----------------- 检查所有原始结果词典 -----------------\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 行星原始位置字典 (planet_pos) \" + \"=\"*20)\n",
    "for key, value in planet_pos.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 宫头原始位置字典 (house_pos) \" + \"=\"*20)\n",
    "for key, value in house_pos.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 小行星原始位置字典 (minor_planet_pos) \" + \"=\"*20)\n",
    "for key, value in minor_planet_pos.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 恒星原始位置字典 (fixed_star_pos) \" + \"=\"*20)\n",
    "for key, value in fixed_star_pos.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "# ── KP ──\n",
    "\n",
    "print(\"=\"*20 + \" KP行星结果字典 (kp_planet_results) \" + \"=\"*20)\n",
    "for key, value in kp_planet_results.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" KP宫位结果字典 (kp_house_results) \" + \"=\"*20)\n",
    "for key, value in kp_house_results.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 行星象征宫位 (kp_planet_sigs) \" + \"=\"*20)\n",
    "for key, value in kp_planet_sigs.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 宫位象征星 (kp_house_sigs) \" + \"=\"*20)\n",
    "for key, value in kp_house_sigs.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 主宰星字典 (kp_ruling_planets) \" + \"=\"*20)\n",
    "print(kp_ruling_planets)\n",
    "\n",
    "\n",
    "# ── 其他 ──\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 行星时数据 (Planetary Hour) \" + \"=\"*20)\n",
    "for key, value in planetary_hour_data.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 行星庙旺陷落配置 (Dignities) \" + \"=\"*20)\n",
    "for key, value in dignities.items():\n",
    "    print(f\"{key}: {value}\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 值日星字典（sunrise_results） \" + \"=\"*20)\n",
    "print(\"sunrise_results:\", sunrise_results)\n",
    "\n",
    "print(\"\\n\" + \"=\"*20 + \" 儒略日 (Julian Day) \" + \"=\"*20)\n",
    "print(jd)"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
